import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/index.module.css'
import Sidebar from '@/component/sidebar'
import { useState } from 'react'
import { Welcome } from '@/component'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const[side, setside] = useState(true)
  return (
    <>
      <Head>
        <title>Book E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar side={side}/> 
        <div className='mobile drag' onClick={() => setside(!side)}>
          <p>{side ? "open" : "close"}</p>
        </div>
        <div className={styles.top}>
          <Welcome/>
          
        </div>
        
      </main>
    </>
  )
}


