import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/index.module.css'
import Sidebar from '@/component/sidebar'
import { useState } from 'react'
import { Popular, Scheduled, Welcome } from '@/component'
import Week from '@/component/schedule/Week'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBars, faTimes} from '@fortawesome/free-solid-svg-icons';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const[side, setside] = useState(true)
  const book = [
    {
      id: 1,
      title: "tears of the sun",
      author: "chinua achebe",
      image: 'book1.png'
    },
    {
      id: 2,
      title: "tears of the sun",
      author: "chinua achebe",
      image: 'book2.png'
    },
    {
      id: 3,
      title: "tears of the sun",
      author: "chinua achebe",
      image: 'book3.png'
    },
    {
      id: 4,
      title: "tears of the sun",
      author: "chinua achebe",
      image: 'book4.png'
    },
    {
      id: 5,
      title: "tears of the sun",
      author: "chinua achebe",
      image: 'book1.png'
    },
    {
      id:6,
      title: "tears of the sun",
      author: "chinua achebe",
      image: 'book1.png'
    },
    {
      id: 7,
      title: "tears of the sun",
      author: "chinua achebe",
      image: 'book2.png'
    },
    {
      id: 8,
      title: "tears of the sun",
      author: "chinua achebe",
      image: 'book3.png'
    }
    
  ]

  return (
    <>
      <Head>
        <title>Book E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar side={side}/> 
        <div className='mobile drag' onClick={() => setside(!side)}>
          <FontAwesomeIcon icon={side ? faBars : faTimes} />
        </div>
        <main className={styles.body_mobile}>
          <div className={styles.top}>
            <Welcome/>
          </div>
          <Popular header = "Popular now" array = {book} length = {450} />
          <Scheduled />
          <Week />
          <Popular header = "New collection" array = {book} length = {450} />
          <Popular header = "comments" array = {book}  length = {1550}/>
        </main>
        <main className={styles.body_desktop}>
          <div className={styles.top}>
            <Welcome/>
            <Scheduled />
          </div>
          <div className={styles.middle}>
            <Popular header = "Popular now" array = {book} length = {250} />
            <Week />
          </div>
          <div className={styles.end}>
            <Popular header = "New collection" array = {book} length = {450} />
            <Popular header = "comments" array = {book}  length = {1550}/>
          </div>
        </main>
      </main>
    </>
  )
}


